"""
cpp_writer.py — context-manager-based C++ file writer.

Tracks indentation and provides helpers for common C++ constructs so
generator code stays focused on what to emit, not how to format it.
"""


class CppWriter:
    """
    Write a single C++ source or header file with consistent formatting.

    Usage:
        with CppWriter("foo.hpp", is_header=True) as w:
            w.pragma_once()
            w.include("cstdint", system=True)
            w.open_namespace("foo")
            w.line("int x = 0;")
            w.close_namespace("foo")
    """

    _INDENT = "    "  # 4-space indent

    def __init__(self, filepath: str, is_header: bool = False):
        self._filepath = filepath
        self._is_header = is_header
        self._indent_level = 0
        self._file = None

    def __enter__(self):
        self._file = open(self._filepath, "w", encoding="utf-8")
        return self

    def __exit__(self, *args):
        if self._file:
            self._file.close()
            self._file = None

    # ------------------------------------------------------------------
    # Core primitives
    # ------------------------------------------------------------------

    def line(self, text: str = ""):
        """Write one line at the current indent level."""
        if text:
            self._file.write(self._INDENT * self._indent_level + text + "\n")
        else:
            self._file.write("\n")

    def blank(self):
        self.line()

    def raw(self, text: str):
        """Write text verbatim — no indent, no newline appended."""
        self._file.write(text)

    # ------------------------------------------------------------------
    # Indentation
    # ------------------------------------------------------------------

    def indent(self):
        self._indent_level += 1

    def dedent(self):
        self._indent_level = max(0, self._indent_level - 1)

    class _IndentCtx:
        def __init__(self, w: "CppWriter"):
            self._w = w
        def __enter__(self):
            self._w.indent()
            return self
        def __exit__(self, *args):
            self._w.dedent()

    def indented(self) -> "_IndentCtx":
        """Context manager: run a block at one extra indent level."""
        return self._IndentCtx(self)

    # ------------------------------------------------------------------
    # Comments
    # ------------------------------------------------------------------

    def comment(self, text: str):
        """// single-line comment."""
        self.line(f"// {text}")

    def block_comment(self, lines: list):
        """
        /* multi-line
         * block comment
         */
        """
        self.line("/*")
        for l in lines:
            self.line(f" * {l}")
        self.line(" */")

    def separator(self, title: str = ""):
        """Visual section divider, optionally labelled."""
        if title:
            pad = "-" * max(0, 56 - len(title))
            self.line(f"// --- {title} {pad}")
        else:
            self.line("// " + "-" * 65)

    # ------------------------------------------------------------------
    # File-level boilerplate
    # ------------------------------------------------------------------

    def generated_header(self, description: str = ""):
        """Standard 'do not edit' comment block, written at the top of each file."""
        lines = ["Generated by AURA device-firmware-gen — do not edit by hand."]
        if description:
            lines.append(description)
        self.block_comment(lines)
        self.blank()

    def pragma_once(self):
        self.line("#pragma once")
        self.blank()

    def include(self, header: str, system: bool = False):
        if system:
            self.line(f"#include <{header}>")
        else:
            self.line(f'#include "{header}"')

    # ------------------------------------------------------------------
    # Namespaces
    # ------------------------------------------------------------------

    def open_namespace(self, name: str):
        self.line(f"namespace {name} {{")
        self.indent()

    def close_namespace(self, name: str):
        self.dedent()
        self.line(f"}} // namespace {name}")

    # ------------------------------------------------------------------
    # Structs
    # ------------------------------------------------------------------

    def open_struct(self, name: str, inherits: str = ""):
        decl = f"struct {name}"
        if inherits:
            decl += f" : {inherits}"
        self.line(decl + " {")
        self.indent()

    def close_struct(self, trailing: str = ""):
        """trailing: optional instance name(s) placed after the closing brace."""
        self.dedent()
        self.line(f"}}{trailing};")

    # ------------------------------------------------------------------
    # Enums
    # ------------------------------------------------------------------

    def open_enum_class(self, name: str, underlying: str = "uint8_t"):
        self.line(f"enum class {name} : {underlying} {{")
        self.indent()

    def close_enum_class(self):
        self.dedent()
        self.line("};")

    def enum_value(self, name: str, value: int, last: bool = False, comment: str = ""):
        comma = "," if not last else ""
        if comment:
            self.line(f"{name} = {value}{comma}  // {comment}")
        else:
            self.line(f"{name} = {value}{comma}")

    # ------------------------------------------------------------------
    # Functions
    # ------------------------------------------------------------------

    def open_function(self, signature: str):
        self.line(signature + " {")
        self.indent()

    def close_function(self):
        self.dedent()
        self.line("}")

    def inline_function(self, signature: str, body: str):
        """Single-expression inline function — no overhead after optimisation."""
        self.line(f"inline {signature} {{ {body} }}")

    # ------------------------------------------------------------------
    # Preprocessor
    # ------------------------------------------------------------------

    def open_ifdef(self, macro: str):
        self.line(f"#ifdef {macro}")

    def open_ifndef(self, macro: str):
        self.line(f"#ifndef {macro}")

    def pp_else(self):
        self.line("#else")

    def close_ifdef(self, macro: str = ""):
        self.line(f"#endif" + (f" // {macro}" if macro else ""))

    def define(self, name: str, value: str = ""):
        self.line(f"#define {name}" + (f" {value}" if value else ""))

    # ------------------------------------------------------------------
    # Generic braced block
    # ------------------------------------------------------------------

    def open_brace(self, header: str = ""):
        self.line((header + " {") if header else "{")
        self.indent()

    def close_brace(self, suffix: str = ""):
        self.dedent()
        self.line("}" + suffix)
